global:
  evaluation_interval: 30s
  scrape_timeout:      30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'fritzbox-upnp-exporter'
    static_configs:
      - targets: ['localhost:8080']