{
 "title": "FritzBox",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Connection uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "fb_wanppp_status_uptime" }
   ]
  },
  {
   "title": "Connection status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "name",
   "targets": [
    { "expr": "fb_wanppp_status_uptime", "legendFormat": "{{status}} / {{ip}}" }
   ]
  },
  {
   "title": "WLAN",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of clients" }
   ],
   "targets": [
    { "expr": "fb_wlan_number_associations", "legendFormat": "{{ssid_standard}}" }
   ]
  },
  {
   "title": "⬆WAN sent total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(fb_wan_total_bytes_sent[$__interval])"
    }
   ]
  },
  {
   "title": "⬇WAN received total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(fb_wan_total_bytes_received[$__interval])"
    }
   ]
  },
  {
   "title": "⬆LAN sent total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(fb_lan_eth_total_bytes_sent[$__interval])"
    }
   ]
  },
  {
   "title": "⬇LAN received total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "expr": "increase(fb_lan_eth_total_bytes_received[$__interval])"
    }
   ]
  },
  {
   "title": "WLAN packet rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "irate(fb_wlan_total_packets_received[5m])",
     "legendFormat": "{{ssid_standard}}"
    }
   ]
  },
  {
   "title": "LAN traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps", "label": "Transferred" }
   ],
   "targets": [
    {
     "expr": "irate(fb_lan_eth_total_bytes_received[30m])*8",
     "legendFormat": "received"
    },
    {
     "expr": "irate(fb_lan_eth_total_bytes_sent[30m])*8",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "WAN packet rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "irate(fb_wan_total_packets_received[5m])",
     "legendFormat": "{{ received  }}"
    },
    {
     "expr": "irate(fb_wan_total_packets_sent[5m])",
     "legendFormat": "{{ sent  }}"
    }
   ]
  },
  {
   "title": "WAN traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bps", "label": "Transferred" }
   ],
   "targets": [
    {
     "expr": "irate(fb_wan_total_bytes_received[5m])*8",
     "legendFormat": "received"
    },
    {
     "expr": "irate(fb_wan_total_bytes_sent[5m])*8",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "LAN packet rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "pps", "label": "rate" }
   ],
   "targets": [
    {
     "expr": "irate(fb_lan_eth_total_bytes_received[15m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(fb_lan_eth_total_bytes_sent[15m])",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}